### PR TITLE
implements a fix for test-breaking changes in 2.12.0-beta.1

### PR DESCRIPTION
**Pull request by maprules1000**
[Switch from custom ember-storage dependency to regular ember-storage and delete fork](https://www.pivotaltracker.com/n/projects/1936891/stories/152906183)

### CODE REVIEW

**Comment by amiel** [comment]
As discussed in Slack. Let's leave this open and point directly to this branch.

**Comment by andreafrost** [comment]
@maprules1000 -- how would you feel about closing this PR?  Is there anything more happening here?

**Comment by andreafrost** [comment]
@maprules1000 -- could you look at this and determine whether we still need to keep an open PR?

**Comment by andreafrost** [comment]
Update: 

@maprules1000 will take care this soon in the following chore: https://www.pivotaltracker.com/story/show/152906183

**Comment by amiel** [comment]
So, we're actually not using this branch anymore. @maprules1000 already upgraded this addon in https://github.com/ActionSprout/fern/commit/048e2d4575 (#3401).

I have accepted the chore as complete and am closing this PR.

**Pull request closed without merging**
